import { Anek_Malayalam } from "next/font/google";
import "../globals.css";
import Header from "@/components/Header";
import GlobalProviders from "@/components/GlobalProviders";
import Footer from "@/components/Footer";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from 'next-intl/server';
import { Toaster } from "@/components/ui/toaster";
const inter = Anek_Malayalam({
  subsets: ["latin"],
  variable: '--font-inter',
  axes:['wdth'],
  weight: ['variable']
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { ...params },
}) {
  const messages = await getMessages();
  return (
    <html lang="en">
      <body className={`${inter.className} ${inter.variable}`}>
        <NextIntlClientProvider messages={messages}>
          <GlobalProviders >
            <Header />
            {children}
            <Footer />
            <Toaster />
          </GlobalProviders>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
